spring.application.name=project1
server.port=8088
server.servlet.context-path=/project1

# MariaDB Configuration
spring.datasource.url=jdbc:mariadb://localhost:3306/project1?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=Anubis@68
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Suppress warnings
logging.level.org.hibernate.orm.jdbc=ERROR
logging.level.org.mariadb.jdbc=ERROR